name: Github Action javascript-obfuscator
uses: KevinRohn/github-action-javascript-obfuscator@v1.1.0
on: [push]
with:
  input_path: main.js
  output_path: obfuscated.js
  compact: true
  control_flow_flattening: false
  dead_code_injection: false
  debug_protection: false
  debug_protection_interval: 0
  log: false
  disable_console_output: true
  rename_globals: false
  string_array_rotate: true
  self_defending: true
  string_array: true
  string_array_encoding: 'none'
  string_array_threshold: 0.75
  unicode_escape_sequence: false
  target: node
